# Generated by Django 4.1.3 on 2023-02-24 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('upload_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.uploadfile')),
            ],
        ),
    ]
