# Generated by Django 4.1.3 on 2023-03-09 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0007_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
